### ISSUE TITLE
能跨就跨，先跨再說

### ISSUE THREAD

**Issue by ejmoog** [GHolk/cjns#13]
# 能跨就跨，先跨再說
2022-03-26 by [ejsoon](https://ejsoon.win/author/ejsoon/)
下面是[維基倉教第五章取碼原則](https://ejmoog.github.io/web/wbcj/wbcj_rull.html)的一段內容：

## 各細則的優先權
由於有些細則需要其他細則的觀念，以上介紹安排了一定順序，但統整而言，若細則彼此衝突，其優先順序是：跨越分則 > 區塊分則 > 精簡原則 > 轉角分則 > 先繁後簡原則。

這個優先權是絕對正確的，大家在編碼和取碼時都必須嚴格遵從。它也是可以遞推的，比如「跨越分則>區塊分則」，那麼就可以推出「跨越分則>精簡原則」、「跨越分則>轉角分則」等等。

既然「跨越分則」是最高取碼原則，它就是至高無尙的，其它取碼原則或分則都必須給它讓路。

比如「覀」的正確編碼只能是「一廿月」，因為「跨越分則>區塊分則」，同時它也符合精簡原則及先繁後簡原則。

再如「甩」的正確編碼只能是「月山」，因為「跨越分則>區塊分則」，同時它也符合精簡原則及先繁後簡原則。

口訣：能跨就跨，先跨再說。

下面評論這個「取碼原則優先權」。

## 二次創新
首先，維基倉教的很多「取碼原則/分則」，都是自主創新研發的，那麼這個「取碼原則優先權」就是他們的二次創新。

他們不是沒有想過要拿到「官方依據」，請看他們跟沈紅蓮之間的對話：

四、倉頡六代中，「步」的取法是「止中的的」而非「卜中火」，而後者相對來説比較精簡，為何不用後者呢？是因為「先繁後簡原則」優於「精簡原則」嗎？
　　回應：是「先繁後簡原則」優於「精簡原則」→原則總是要有先有後的，如果有矛盾，請告知。

沈紅蓮的回答直接讓四傑傻眼。之後，這個「優先權」規則就再也寫不下去了。

這就是為甚麼我們感覺這條規則只寫了個開頭的原因。

## 連作者也一頭霧水
騎沈四傑就在這短短的一句話裏面，把各種取碼原則長拴一鏈。裏面包含了極其複雜的邏輯，不僅讀者們不可能理解和掌握，就連編輯者本身也是一頭霧水。

ichirou就曾發表過對這條規則的意見，他在《對「維基教科書 – 倉頡輸入法」新改版的批評》文章中寫道：

新版增加了『各細則的優先權』，說『由於有些細則需要其他細則的觀念，以上介紹安排了一定順序，但統整而言，若細則彼此衝突，其優先順序是：跨越分則 > 區塊分則 > 精簡原則 > 轉角分則 > 先繁後簡原則。』這個次序值得討論。

但是後来並沒有見到有人在討論。可能是因為搞不懂，所以不敢多說吧。

## 這是一條無法舉例的規則
倉頡輸入法的每一條規則敍述都是必須能被理解和運用的，因此每一條規則都應該可以舉例說明。然而維基倉教的這個規則，不僅舉不出例子，還不斷遭遇反例。

一貫廢話連篇過份舉例的騎沈四傑，寫到這裏倒是挺精簡的。

那麼他們為甚麼拉不出例子来呢？

原因是騎沈四傑思維能力低下，同時這條規則又複雜到了一種境界。它的完整敍述為：

跨越分則 > 區塊分則
跨越分則 > 精簡原則
跨越分則 > 轉角分則
跨越分則 > 先繁後簡原則
區塊分則 > 精簡原則
區塊分則 > 轉角分則
區塊分則 > 先繁後簡原則
精簡原則 > 轉角分則
精簡原則 > 先繁後簡原則
轉角分則 > 先繁後簡原則
現在大家知道四傑的苦衷了吧？如果每個優先權都需要舉例，還不能有反例，以cj6、ichirou、ceku、馬拉錘的智商，根本辦不到。

乾脆還是不舉了吧！所以維基倉教這句規則就一個例子也沒有了。

## 這條規則是錯誤的
「取碼原則優先權」這條規則敍述是絕對錯誤的。倉頡輸入法的各個取碼原則是相互契合的，各有適用範圍。不能說哪個一定比哪個強，也不是每個原則都會在同一處發生干涉。

比如「折彎特徵」（也就是轉角分則）是最強的取碼原則，它是必須遵守的，一旦該折彎被識別，它就必須保留。而它也根本不可能跟「跨越分則」、「區塊分則」在同一處發生競爭，因此它是不能跟其它原則長拴一鏈的。

縱貫與横截（也就是跨越分則與區塊分則）也沒有說有絕對的先後次序。維倉三編看到了一些字最終是採取了跨越，就以為跨越一定優先於區塊。但是為何「覀甩」又不是跨越優先？再如漢文庫典的「毋曱甴」等，都沒有優先跨越。

再如「失」字不取作├大，「生」不取├土；而「本」卻取作木一，「必」取作心㇒。這些例子都說明了，各原則之間並沒有絕對的先後優先次序。

揔結
維基倉教的「各細則優先權」沒有任何的官方依據，它是騎沈四傑的二次創新。
這條規則雖然簡短，但是異常複雜。不僅讀者無法理解運用，編輯者本身也是一頭霧水。
由於不是一條可以應用的規則敍述，連一個例子都拉不出来。
這條規則是絕對錯誤的，因為不同的取碼原則有不同的適用範圍，不能說哪個原則一定比哪個強。

**Comment by GHolk** [comment]
請不要在此 repo 發無關倉頡新星的內容，勸告不聽者封鎖
